# Generated by Django 6.0.1 on 2026-01-16 16:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('zona', models.CharField(choices=[('milagro', 'Milagro'), ('huanchaco', 'Huanchaco'), ('buenos aires', 'Buenos Aires')], max_length=20, verbose_name='Zona asignada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cobrador',
                'verbose_name_plural': 'Cobradores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cama 2 plazas, Colchón Orthopedic, Ropero 4 puertas', max_length=255, unique=True, verbose_name='Nombre del producto')),
                ('categoria', models.CharField(choices=[('camas', 'Camas'), ('colchones', 'Colchones'), ('roperos', 'Roperos'), ('muebles_sala', 'Muebles de Sala'), ('comedores', 'Comedores'), ('electrodomesticos', 'Electrodomésticos'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría')),
                ('precio_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio sugerido')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar productos que ya no se venden', verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['nombre'], name='charito_pro_nombre_8c5d33_idx'), models.Index(fields=['categoria', 'activo'], name='charito_pro_categor_ef7ad6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de venta')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('lugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar/Sector')),
                ('zona', models.CharField(choices=[('milagro', 'Milagro'), ('huanchaco', 'Huanchaco'), ('buenos aires', 'Buenos Aires')], max_length=20, verbose_name='Zona')),
                ('descripcion_adicional', models.CharField(blank=True, help_text='Detalles específicos de este producto (color, modelo, etc.)', max_length=255, null=True, verbose_name='Descripción adicional')),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio con el que se hizo la venta originalmente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio total de venta')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto desde el cual comenzará a descontar los pagos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Saldo inicial/actual')),
                ('inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto inicial pagado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo pendiente')),
                ('frecuencia_pago', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], max_length=20, verbose_name='Frecuencia de pago')),
                ('dia_cobro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Día de cobranza')),
                ('fecha_inicial', models.DateField(blank=True, help_text='Fecha del primer pago (inicial o primer abono)', null=True, verbose_name='Fecha del pago inicial')),
                ('primer_pago_registrado', models.BooleanField(default=False, verbose_name='Primer pago registrado')),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recogido', 'Recogido'), ('controlar', 'Controlar'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='charito.cobrador', verbose_name='Cobrador asignado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='charito.producto', verbose_name='Producto')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Venta/Contrato',
                'verbose_name_plural': 'Ventas/Contratos',
                'ordering': ['-fecha_venta', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto pagado')),
                ('es_primer_pago', models.BooleanField(default=False, verbose_name='Es el primer pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cobrados', to='charito.cobrador', verbose_name='Cobrador que recibió el pago')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='charito.venta', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_contrato'], name='charito_ven_numero__8b2998_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['zona', 'cobrador'], name='charito_ven_zona_f7e8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='charito_ven_estado_e0bfab_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['producto', 'fecha_venta'], name='charito_ven_product_5cdcac_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='charito_pag_fecha_p_dcb6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cobrador', 'fecha_pago'], name='charito_pag_cobrado_202cf2_idx'),
        ),
    ]
