# Generated by Django 6.0.1 on 2026-01-19 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta', '-fecha_registro']},
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='charito_ven_numero__8b2998_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='charito_ven_zona_f7e8d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='charito_ven_estado_e0bfab_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='charito_ven_product_5cdcac_idx',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cobrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='charito.cobrador'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='dia_cobro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recogido', 'Recogido'), ('controlar', 'Controlar'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='frecuencia_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_contrato',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='primer_pago_registrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='charito.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='zona',
            field=models.CharField(choices=[('milagro', 'Milagro'), ('huanchaco', 'Huanchaco'), ('buenos aires', 'Buenos Aires')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descripcion_adicional',
        ),
    ]
