# Generated by Django 6.0.1 on 2026-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charito', '0002_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recogido', 'Recogido'), ('controlar', 'Controlar'), ('bajada', 'Bajada'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
