# Generated by Django 6.0.1 on 2026-02-17 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charito', '0003_alter_venta_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['venta', '-fecha_pago', '-fecha_registro'], name='charito_pag_venta_i_798a76_idx'),
        ),
    ]
