# Generated by Django 6.0.1 on 2026-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charito', '0004_pago_charito_pag_venta_i_798a76_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_descuento',
            field=models.BooleanField(default=False, verbose_name='Es descuento'),
        ),
    ]
